# Generated by Django 4.2.16 on 2024-10-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
        migrations.AddField(
            model_name='team',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
