# Generated by Django 4.2.16 on 2024-10-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_team_country_team_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='number',
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(default='PL', max_length=2),
        ),
    ]
