# Generated by Django 4.2.16 on 2024-10-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_remove_team_number_team_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pub_date', models.DateField(verbose_name='Date Published')),
                ('phone_number', models.IntegerField(default=0)),
            ],
        ),
    ]
