# Generated by Django 4.2.16 on 2024-10-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='phone_number',
            new_name='workers',
        ),
    ]
