# Generated by Django 4.2.16 on 2024-10-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_stanowisko_osoba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.CharField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna'), (3, 'Inne')], max_length=20),
        ),
    ]
